/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.main.view;


import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import src.main.model.RegistroDAO;
import static src.main.view.NewJFrame.panel_centro;
/**
 *
 * @author lococ
 */
public class panel_registro extends javax.swing.JPanel {
    /**
     * Creates new form panel_registro
     */
    
    public panel_registro() {
        initComponents();
        ObtenerFechaActual();
       
    }
 private void Showpanel(JPanel p){
       
        p.setSize(723, 580);
        p.setLocation(0,0);
         
        
        panel_centro.removeAll();
        panel_centro.add(p);
        panel_centro.repaint();
        panel_centro.validate();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movimento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_codigoP = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JFormattedTextField();
        rb_E = new javax.swing.JRadioButton();
        rb_S = new javax.swing.JRadioButton();
        txt_cantidad = new javax.swing.JTextField();

        setFocusCycleRoot(true);
        setFocusTraversalPolicyProvider(true);
        setPreferredSize(new java.awt.Dimension(773, 573));
        setLayout(new java.awt.BorderLayout());
        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txt_codigoP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Codigo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txt_nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/savetheapplication_guardar_2958.png"))); // NOI18N
        btn_guardar.setText("Guardar (F12)");
        btn_guardar.setBorderPainted(false);
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/savetheapplication_guardar_2958 (1).png"))); // NOI18N
        btn_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_descripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Descripción", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Regristrar un Nuevo Articulo");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_fecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fecha:dd/mm/yy", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        txt_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        movimento.add(rb_E);
        rb_E.setSelected(true);
        rb_E.setText("Entrada");

        movimento.add(rb_S);
        rb_S.setText("Salida");

        txt_cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cantidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_codigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rb_E)
                                .addGap(18, 18, 18)
                                .addComponent(rb_S)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btn_guardar)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_codigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_E)
                    .addComponent(rb_S)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    public void ObtenerFechaActual() {
        // Obtener la fecha actual
        Date fechaActual = new Date();

        // Definir el formato deseado para la fecha
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

        // Formatear la fecha actual según el formato deseado
        String fechaFormateada = formatoFecha.format(fechaActual);

        // Imprimir la fecha actual formateada
        txt_fecha.setText(fechaFormateada);
}

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        try {
            String movimiento1=null;
            RegistroDAO r=new RegistroDAO();
            r.realizarRegistroProducto(txt_codigoP.getText(), txt_nombre.getText(), txt_descripcion.getText());
                if (panel_registro.rb_E.isSelected()) {
                movimiento1 = "E";
                } else if (panel_registro.rb_S.isSelected()) {
                movimiento1 = "S";
                }
            int cantidad=Integer.parseInt(txt_cantidad.getText());
            
            r.realizarRegistroMovimiento(txt_codigoP.getText(),movimiento1, txt_fecha.getText(),cantidad );
             txt_codigoP.setText("");
            txt_descripcion.setText("");
            txt_nombre.setText("");
            txt_cantidad.setText("");
            
        } catch (Exception e)  { JOptionPane.showMessageDialog(this, "Error al Guardar: " +e);
        }
        
         
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyPressed
         int keyCode = evt.getKeyCode();
        
        if (keyCode == java.awt.event.KeyEvent.VK_F12) {
            try {
            String movimiento1=null;
            RegistroDAO r=new RegistroDAO();
            r.realizarRegistroProducto(txt_codigoP.getText(), txt_nombre.getText(), txt_descripcion.getText());
                if (panel_registro.rb_E.isSelected()) {
                movimiento1 = "E";
                } else if (panel_registro.rb_S.isSelected()) {
                movimiento1 = "S";
                }
            int cantidad=Integer.parseInt(txt_cantidad.getText());
            
            r.realizarRegistroMovimiento(txt_codigoP.getText(),movimiento1, txt_fecha.getText(),cantidad );
            txt_codigoP.setText("");
            txt_descripcion.setText("");
            txt_nombre.setText("");
            txt_cantidad.setText("");
            
        } catch (Exception e)  { JOptionPane.showMessageDialog(this, "Error al Guardar: " +e);
        }
        }
    }//GEN-LAST:event_txt_cantidadKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_guardar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.ButtonGroup movimento;
    public static javax.swing.JRadioButton rb_E;
    public static javax.swing.JRadioButton rb_S;
    public static javax.swing.JTextField txt_cantidad;
    public static javax.swing.JTextField txt_codigoP;
    public static javax.swing.JTextField txt_descripcion;
    public static javax.swing.JFormattedTextField txt_fecha;
    public static javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
